## Import the numpy package under the name np and Print the numpy version and the configuration 

In [1]:
import numpy as np

print("numpy version :" ,np.__version__)
print("numpy configuration: ",np.show_config())

numpy version : 1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
numpy configuration:  None


## Create a null vector of size 10

In [2]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Create Simple 1-D array and check type and check data types in array

In [4]:
arr = np.arange(0,10)
print(arr)
print(type(arr))
print(arr.dtype)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int64


## How to find number of dimensions, bytes per element and bytes of memory used?

In [6]:
print("Dimensions: ",arr.ndim)
print("bytes per element: ",arr.itemsize)
print("Bytes per memory: ",arr.nbytes)

Dimensions:  1
bytes per element:  8
Bytes per memory:  80


## Create a null vector of size 10 but the fifth value which is 1

In [7]:
v = np.zeros(10)
v[4]=1
print(v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## Create a vector with values ranging from 10 to 49

In [8]:
vec = np.arange(10,50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## Reverse a vector (first element becomes last)

In [9]:
vec[::-1]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
m = np.arange(0,9)
m.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Find indices of non-zero elements from [1,2,0,0,4,0]

In [11]:
v = [1,2,0,0,4,0]
np.nonzero(v)

(array([0, 1, 4]),)

## Create a 3x3 identity matrix

In [12]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Create a 3x3x3 array with random values

In [17]:
import random

a = np.random.random((3,3,3))
print(a)

[[[0.59252547 0.3097549  0.32702011]
  [0.36381034 0.39776855 0.45560086]
  [0.26865239 0.67982609 0.14800163]]

 [[0.2271137  0.0600399  0.61265522]
  [0.55348113 0.6780911  0.75019025]
  [0.94420332 0.25161875 0.74642333]]

 [[0.98372153 0.0797185  0.92949108]
  [0.58315954 0.67563203 0.65005131]
  [0.37899333 0.29810164 0.81081684]]]


## Create a 10x10 array with random values and find the minimum and maximum values

In [18]:
a = np.random.random((10,10))
print(a)
print("Maximum value:" ,np.max(a))
print("Minimum value:" ,np.min(a))


[[0.65828948 0.0877018  0.78007392 0.54881239 0.19494961 0.34811957
  0.06453538 0.07042764 0.88509796 0.75786818]
 [0.0233234  0.37583715 0.18948776 0.9962942  0.82207728 0.505271
  0.95088179 0.1366362  0.6063443  0.50141222]
 [0.16491834 0.46026619 0.79262639 0.51452027 0.41738708 0.00407492
  0.75488065 0.81996463 0.87132095 0.0482864 ]
 [0.63405427 0.93340666 0.13989144 0.09634604 0.02549605 0.33724943
  0.45947006 0.42464558 0.96758806 0.04784843]
 [0.81747038 0.95374018 0.29727071 0.66126027 0.18069189 0.06816229
  0.55618059 0.13704297 0.51629564 0.84391569]
 [0.82331773 0.98225804 0.22089324 0.95790697 0.88260895 0.65956501
  0.67206474 0.37737241 0.34099893 0.8732492 ]
 [0.30171022 0.41348195 0.13393401 0.09120673 0.21227479 0.37707546
  0.736561   0.1382267  0.89649356 0.79166339]
 [0.42497357 0.59956218 0.27787665 0.46820154 0.59681616 0.04333404
  0.30163647 0.18801909 0.71416078 0.82227447]
 [0.72090621 0.6597091  0.07780664 0.08688577 0.74103737 0.85671848
  0.84947752 0

## Create a random vector of size 30 and find the mean value

In [19]:
v = np.random.random((5,6))

print("Mean=",np.mean(v))

Mean= 0.5391569514132843


## Create a 2d array with 1 on the border and 0 inside

In [20]:
d = np.ones((5,5))

d[1:4,1:4]=0

print(d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## How to add a border (filled with 0's) around an existing array?

In [25]:
a = np.ones((5,5))

a[:1,:]=0
a[-1:,:]=0
a[:,:1]=0
a[:,-1:]=0
print(a)




[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


## How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?

Example - [[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20

In [33]:
a = np.arange(1,15).reshape(2,7)
print(type(a))
print("Getting 13 value",a[1][5])
print("First row: ",a[0,:])
print("Third Column: ", a[:,3])
print("Getting [2,4,6]: ",a[0,1::2])


<class 'numpy.ndarray'>
Getting 13 value 13
First row:  [1 2 3 4 5 6 7]
Third Column:  [ 4 11]
Getting [2,4,6]:  [2 4 6]


## How to Convert a 1D array to a 2D array with 2 rows

In [38]:
ar = np.arange(1,11)
print(ar.reshape(2,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

a = np.array([1,2,3])`
Desired Output:

#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [44]:
a = np.array([1,2,3])
print(a)
print(np.append(np.repeat(a,3),np.tile(a,3)))

[1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


## Write a program to show how Numpy taking less memory compared to Python List?

In [45]:
l = range(100)
a = 2

import sys

print("Memory Occupies by list:" ,sys.getsizeof(a)*len(l))

al = np.arange(100)

print("Size of Numpy: ", al.size * al.itemsize)

Memory Occupies by list: 2800
Size of Numpy:  800


## Write a program to show how Numpy taking less time compared to Python List?

In [47]:
import sys
import time



size = 10000

l1 = range(size)
l2 = range(size)
start = time.time()
r = [i*j for i,j in zip(l1,l2)]

print("Time taken by list= ",time.time()-start,"Seconds")

n1 = np.arange(size)

n2 = np.arange(size)
start1 = time.time()

re = n1*n2


print("Time taken by numpy = {} seconds".format(time.time()-start1))

Time taken by list=  0.0014691352844238281 Seconds
Time taken by numpy = 0.0002741813659667969 seconds
